apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: perms-operator
spec:
  channel: {{ .Values.subscription_channel }}
  name: perms
  source: {{ .Values.catalog_name }}
  sourceNamespace: {{ .Values.catalog_namespace }}
  installPlanApproval: Manual