# permissions for end users to view permsclusterrolebindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: permsclusterrolebinding-viewer-role
rules:
- apiGroups:
  - perms.infra-mgmt.io
  resources:
  - permsclusterrolebindings
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - perms.infra-mgmt.io
  resources:
  - permsclusterrolebindings/status
  verbs:
  - get
