# permissions for end users to edit permsrolebindings.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: permsrolebinding-editor-role
rules:
- apiGroups:
  - perms.infra-mgmt.io
  resources:
  - permsrolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - perms.infra-mgmt.io
  resources:
  - permsrolebindings/status
  verbs:
  - get
