---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - perms.infra-mgmt.io
  resources:
  - permsrolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - perms.infra-mgmt.io
  resources:
  - permsrolebindings/finalizers
  verbs:
  - update
- apiGroups:
  - perms.infra-mgmt.io
  resources:
  - permsrolebindings/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - bind
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
