{{- range $permission := .Values.permissions }}
{{- $release_namespace := list $.Release.Namespace }}
{{- $namespace_list := $permission.namespaces | default $release_namespace}}
{{- range $namespace := $namespace_list}}
---
apiVersion: perms.infra-mgmt.io/v1beta1
kind: PermsRoleBinding
metadata:
  name: "{{$permission.name}}"
  namespace: {{$namespace}}
  labels:
    app.kubernetes.io/name: {{ $.Chart.Name | quote}}
    helm.sh/chart: {{ $.Chart.Name }}-{{ $.Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ $.Release.Service | quote}}
    app.kubernetes.io/instance: {{ $.Release.Name | quote}}
    app.kubernetes.io/version: {{ $.Chart.AppVersion | quote}}
spec:
  role: "{{$permission.role.name}}"
  kind: "{{$permission.role.kind}}"
  groups:
  {{- range $group := $permission.groups}}
    - {{$group}}
  {{- end }}
  user:
    {{- range $user := $permission.user}}
    - {{$user}}
  {{- end }}
  serviceaccounts:
  {{- range $sa := $permission.serviceaccounts}}
    - name: "{{$sa.name}}"
      namespace: "{{$sa.namespace}}"
  {{- end}}

{{- end }}
{{- end }}