name: Build and Publish Operator Bundle

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'
defaults:
  run:
    shell: bash

permissions: 
  packages: write
  contents: read
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Get the repository's code
      - name: Checkout
        uses: actions/checkout@v3
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Set up Go
        id: go
        uses: actions/setup-go@v3
      - name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Operator SDK
        run: |
          export ARCH=$(case $(uname -m) in x86_64) echo -n amd64 ;; aarch64) echo -n arm64 ;; *) echo -n $(uname -m) ;; esac) && \
          export OS=$(uname | awk '{print tolower($0)}') && \
          export OPERATOR_SDK_DL_URL=https://github.com/operator-framework/operator-sdk/releases/download/v1.22.2 && \
          curl -LO ${OPERATOR_SDK_DL_URL}/operator-sdk_${OS}_${ARCH} && \
          gpg --keyserver keyserver.ubuntu.com --recv-keys 052996E2A20B5C7E && \
          curl -LO ${OPERATOR_SDK_DL_URL}/checksums.txt && \
          curl -LO ${OPERATOR_SDK_DL_URL}/checksums.txt.asc && \
          gpg -u "Operator SDK (release) <cncf-operator-sdk@cncf.io>" --verify checksums.txt.asc && \
          grep operator-sdk_${OS}_${ARCH} checksums.txt | sha256sum -c - && \
          chmod +x operator-sdk_${OS}_${ARCH} && sudo mv operator-sdk_${OS}_${ARCH} /usr/local/bin/operator-sdk
      - name: Docker meta
        id: tagging # you'll use this in the next step
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/infra-mgmt-io/perms-bundle
          # Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=semver,pattern={{raw}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
      - name: Operator bundle verify
        run: operator-sdk bundle validate ./bundle
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: bundle.Dockerfile
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.tagging.outputs.tags }}
          labels: ${{ steps.tagging.outputs.labels }}